name: desafio-ci-sonarcloud
on:
  pull_request:
    branches:
      - develop 

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.11

      - name: Install dependencies
        run: yarn
      - name: Test and coverage
        run: yarn jest --coverage

      - run: npm install
      - run: npm test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}